### ISSUE TITLE
Bug $near on version 6.1.4 not working, 6.1.3 return wrong total ( collection total, not total found )

### ISSUE THREAD

**Issue by Polqk** [feathersjs-ecosystem/feathers-mongoose#264]
Hello,

I had problem with $near since 2 weeks
you can see me mongoose issue here : https://github.com/Automattic/mongoose/issues/6981

, and the issue was to set feathers-mongoose to v6.1.3 but in 6.1.3 there is another bug : 
total in request response is always equal to collection size in database and not results found

Thanks

**Comment by daffl** [comment]
Other than the counting documents behaviour, nothing changed in those releases. First, I'd recommend making sure that you are getting the same Mongoose version (`npm ls mongoose`) on both, `feathers-mongoose` 6.1.2 and 6.1.4.

**Comment by cbeninati** [comment]
@Polqk So, just as @daffl said, the change to counting documents was the only difference between releases. And it also happens to break `$geoNear, $near, $nearSphere` queries.

> Other than the counting documents behaviour, nothing changed in those releases.

Anyway, the fix is simple. When instantiating your mongoose service, set the `useEstimatedDocumentCount` option to `true`.

```js
const createService = require('feathers-mongoose');

createService({ useEstimatedDocumentCount: true });
```

**Comment by Polqk** [comment]
@cbeninati Thanks for the solution
